oneapi-src/level-zero-tests

negative_tests/core/test_module_errors/src/test_module_errors.cpp
Depends on https://github.com/oneapi-src/level-zero/pull/9. [FreeBSD](https://github.com/freebsd/freebsd/commit/c8ed04c26b6758354853a6bed4629f71d0d01a7d) and [OpenBSD](https://github.com/openbsd/src/commit/6ecde746dea9a5d17abf3bafa06c232b9189b33b) define `NULL` via `nullptr` in C++11 mode.
<details><summary>Tests output (some fail)</summary>
```
test 1
Start 1: image_tests
1: Test command: utils/image/image_tests
1: Test timeout computed to be: 10000000
1: [==========] Running 21 tests from 7 test cases.
1: [----------] Global test environment set-up.
1: [----------] 2 tests from ImagePNG32Bit
1: [ RUN      ] ImagePNG32Bit.GetPixel
1: [       OK ] ImagePNG32Bit.GetPixel (0 ms)
1: [ RUN      ] ImagePNG32Bit.SetPixel
1: [       OK ] ImagePNG32Bit.SetPixel (0 ms)
1: [----------] 2 tests from …
```
=> Unbreak build on FreeBSD

perf_tests/common/src/ze_app.cpp, perf_tests/ze_peak/src/ze_peak.cpp
That will make descriptor consistent between runs
=> Zero initialize command list/command queue descriptors in perf tests

utils/test_harness/src/test_harness_module.cpp
One of the `lzt::create_module` overloads takes `context` as an argument but uses `lzt::get_default_context()` instead. 
It can result in errors in some tests (e.g. `test_barrier.cpp` : `GivenKernelFunctionsAndMemoryCopyWhenBarrierInsertedThenExecutionCompletesSuccesfully`).
=> Fix context while creating Level Zero module

conformance_tests/sysman/test_sysman_ras/src/test_sysman_ras.cpp, utils/test_harness/sysman/include/test_harness_sysman_ras.hpp, utils/test_harness/sysman/src/test_harness_sysman_ras.cpp
Related-to: VLCLJ-2135
Signed-off-by: Vishnu Khanth [vishnu.khanth.b@intel.com](mailto:vishnu.khanth.b@intel.com)
=> Add CTS for RasGetStateExp and ClearStateExp

conformance_tests/sysman/test_sysman_device/src/test_sysman_device.cpp, utils/test_harness/sysman/include/test_harness_sysman_device.hpp, utils/test_harness/sysman/src/test_harness_sysman_device.cpp
Related-to: VLCLJ-2115
Signed-off-by: Vishnu Khanth [vishnu.khanth.b@intel.com](mailto:vishnu.khanth.b@intel.com)
=> Add CTS to validate device reset ext

conformance_tests/sysman/test_sysman_device/src/test_sysman_device.cpp, conformance_tests/sysman/test_sysman_init/src/test_init.cpp
=> Fix Sysman CTS bug in Device & Init suites

conformance_tests/sysman/test_sysman_device/src/test_sysman_device.cpp, conformance_tests/sysman/test_sysman_init/src/test_init.cpp
* Add nullptr check for returns form getenv to avoid sigsegv.
* Passing char[] for putenv instead of string constant to avoid compilation warning.
Related-To: VLCLJ-2228
=> fix: Resolve nullptr access issues

conformance_tests/sysman/test_sysman_device/src/test_sysman_device.cpp, conformance_tests/sysman/test_sysman_engine/src/test_sysman_engine.cpp, conformance_tests/sysman/test_sysman_frequency/src/test_sysman_frequency.cpp, conformance_tests/sysman/test_sysman_memory/src/test_sysman_memory.cpp
=> test: CTS for zesDeviceGetSubDeviceProperties API

conformance_tests/sysman/test_sysman_device/src/test_sysman_device.cpp, conformance_tests/sysman/test_sysman_device/src/test_sysman_device_helper.cpp
*  zesDeviceGetSubDevicePropertiesExp is used to retrieve Subdevice UUID's.
* Sysman UUID's are compared with Core UUID's (FLAT Mode)
Related-To: VLCLJ-2256
=> Add CTS for Sysmandevicemapping to verify UUID's

conformance_tests/tools/debug/src/test_debug_utils.cpp
Segmentation fault is seen on some CTS tests when validation layer is enabled due to uninitialized memory pointer.
Related To: VLCLJ-2260
=> Fix segmentation fault due to uninitialized memory pointer.

utils/test_harness/src/test_harness_event.cpp
* get correct device properties based on property type
=> Fix get_timestamp_context_duration in test_harness_event

conformance_tests/tools/debug/src/test_debug_helper.cpp
This is needed for another tests that will be implemented in the future and will use this test type.
=> Use custom module build options in LONG_RUNNING_KERNEL_INTERRUPTED test type

perf_tests/ze_peak/src/global_bw.cpp, perf_tests/ze_peak/src/transfer_bw.cpp, perf_tests/ze_peak/src/ze_peak.cpp
The explicit scaling code for ze_peak violates L0 spec and has no overlap between sub-devices. This PR corrects these issues.
=> Fix ze_peak explicit scaling benchmark

utils/test_harness/tools/src/test_harness_metric.cpp
Replace deprecated ZET_METRIC_TYPE_IP_EXP with ZET_METRIC_TYPE_IP
Resolves: [VLCLJ-2328](https://jira.devtools.intel.com/browse/VLCLJ-2328)
=> fix: update metric_type

conformance_tests/core/test_event/src/test_event.cpp
The test takes too much time on the simulators, reduce the number of thread groups and iterations
=> fix: reduce the number of thread groups in event independence tests

utils/test_harness/tools/include/test_harness_debug.hpp, utils/test_harness/tools/src/test_harness_debug.cpp
Written a function instead of writing full code every time when needed.
=> Function to check for heapless mode

conformance_tests/tools/metrics/src/test_metric.cpp, utils/test_harness/tools/include/test_harness_metric.hpp, utils/test_harness/tools/src/test_harness_metric.cpp
=> fix: Enhance streamer tests

conformance_tests/core/test_ipc/src/test_ipc_memory.cpp, conformance_tests/core/test_ipc/src/test_ipc_multidevice.cpp, conformance_tests/core/test_ipc/src/test_ipc_multisubdevice.cpp, conformance_tests/core/test_ipc/src/test_ipc_put_handle.cpp, conformance_tests/core/test_memory/src/test_virtual_memory.cpp, conformance_tests/core/test_p2p/src/test_p2p.cpp, conformance_tests/core/test_p2p/src/test_p2p_mem_access.cpp, layer_tests/tracing/src/test_api_ltracing.cpp, layer_tests/tracing/src/test_api_ltracing_compat.cpp, utils/test_harness/include/test_harness/test_harness_memory.hpp, utils/test_harness/src/test_harness_memory.cpp
=> feature: add physical system memory tests 1/n

conformance_tests/tools/metrics/src/test_metric.cpp
Resolves: [VLCLJ-2336](https://jira.devtools.intel.com/browse/VLCLJ-2336)
=> fix: comply with revised GTEST_SKIP() guidelines

negative_tests/core/test_driver_errors/src/test_driver_errors.cpp
- Fixed result check in GivenCallToZeInitDriversWithNullPointerCountThenExpectFailure to check for the boolean value for result ==
ZE_RESULT_ERROR_INVALID_NULL_POINTER
=> Fix to Boolean result check in negative test

conformance_tests/sysman/test_sysman_memory/src/test_sysman_memory.cpp
During the call to fetch the memory and the RAS states, the condition variable check has been removed.
Related-To: VLCLJ-2343
Signed-off-by: Pratik Bari <pratik.bari@intel.com>
=> fix: Removed the condition variable check from Sysman Memory CTS

conformance_tests/core/test_ipc/src/test_ipc_event.cpp, conformance_tests/core/test_ipc/src/test_ipc_event_helper.cpp, conformance_tests/tools/debug/src/test_debug_helper.cpp, conformance_tests/tools/metrics/src/test_metric.cpp
=> Fix ipc event timstamp test cases

conformance_tests/sysman/test_sysman_power/src/test_sysman_power.cpp
Related-To: NEO-13701
Signed-off-by: Anvesh Bakwad <anvesh.bakwad@intel.com>
=> Update Power CTS to remove Card Power Domain specific tests

conformance_tests/sysman/test_sysman_diagnostics/src/test_sysman_diagnostics.cpp
=> test: Add CTS for Sysman memory diagnostics

conformance_tests/core/test_copy/src/test_copy_events.cpp
With UMD-managed migrations, it is illegal to access an USM-allocation
from CPU side while it is still in use on GPU side. In such scenario
a CPU-side access triggers data fetch from GPU-side and then any
subsequent GPU-side modification will not be observable on the CPU-side.
With UMD-managed migrations there is no way to tell the GPU that it
should fetch the allocation again from CPU-side before modifying it.
Therefore the `EXPECT_NE` statements can only be called when concurrent
access to USM-allocations is supported.
Signed-off-by: Maciej Bielski <maciej.bielski@intel.com>
=> fix: do not access UMD-managed SVM-allocation while in-use

conformance_tests/core/test_cmdlist/src/test_cmdlist_mixed.cpp
* With this commit test suite names will be named instead of giving numbers. Example:
InterdependCMDListsPipeliningParameterization/zeTestMixedCMDListsInterdependPipelining. GivenRegularCMDListOnComputeEngineAndImmCMDListOnCopyEngineThenCorrectResultsAreReturned/compute_cmd_queue_flag_0_copy_cmd_queue_flag_0_cmd_list_flag_0_using_event # GetParam() = (0, 0, 0, true) GivenRegularCMDListOnComputeEngineAndImmCMDListOnCopyEngineThenCorrectResultsAreReturned/compute_cmd_queue_flag_0_copy_cmd_queue_flag_0_cmd_list_flag_0_not_using_event # GetParam() = (0, 0, 0, false) GivenRegularCMDListOnComputeEngineAndImmCMDListOnCopyEngineThenCorrectResultsAreReturned/compute_cmd_queue_flag_0_copy_cmd_queue_flag_0_cmd_list_flag_1_using_event # GetParam() = (0, 0, 1, true) …
=> Provide meaningful subset test names

utils/test_harness/tools/include/test_harness_debug.hpp
Add declaration of following functions to .hpp file so that can be used by other files
to remove duplication of code.
get_register_set_props
printRegSetProperties
=> Add declaration of functions

negative_tests/core/test_device_errors/src/test_device_errors.cpp, negative_tests/sysman/test_device_errors/src/test_zesdevice_errors.cpp, negative_tests/tools/metric_errors/src/test_metric_errors.cpp
After removal of the stype/pnext check in the validation layer, remove these negative tests until the functionality can be reworked.
=> Remove stype validation checks

layer_tests/tracing/src/main.cpp, layer_tests/tracing/src/test_api_ltracing.cpp, layer_tests/tracing/src/test_api_ltracing_compat.cpp, layer_tests/tracing/src/test_api_ltracing_threading.cpp
-Addresses the issue with dynamic tracing tests running without a gtest filter, this properly resets the tracing for each test run.
=> Fix dynamic tracing cts to reinit tracing

conformance_tests/core/test_mutable_cmdlist/src/test_mutable_cmdlist.cpp
Signed-off-by: Aleksander Czerwionka <aleksander.czerwionka@intel.com>
=> MCL complex scenario test

conformance_tests/core/test_cmdlist/src/test_cmdlist.cpp, conformance_tests/core/test_cmdlist/src/test_cmdlist_immediate.cpp, conformance_tests/core/test_cmdlist/src/test_cmdlist_mixed.cpp, conformance_tests/core/test_copy/src/test_copy.cpp, conformance_tests/core/test_copy/src/test_kernel_copy.cpp, conformance_tests/core/test_memory/src/test_memory.cpp, conformance_tests/core/test_memory_overcommit/src/test_memory_overcommit.cpp, conformance_tests/core/test_module/src/test_cooperative_kernel.cpp, conformance_tests/core/test_module/src/test_module.cpp, conformance_tests/core/test_residency/src/test_residency.cpp, utils/test_harness/include/test_harness/test_harness_memory.hpp, utils/test_harness/src/test_harness_memory.cpp
The function `gtest_skip_if_shared_system_alloc_unsupported` is supposed to exit a shared system allocation test if the system doesn't support shared system allocations. However, the `GTEST_SKIP` macro inside the function only returns from the function instead of exiting the test, thus continuing the rest of the test. 
This PR fixes this my replacing `gtest_skip_if_shared_system_alloc_unsupported` with a macro and adds some inline functions to streamline checks for shared system allocation support.
Related-To: [VLCLJ-2502](https://jira.devtools.intel.com/browse/VLCLJ-2502)
=> Fix: replace gtest_skip_if_shared_system_alloc_unsupported to stop shared system allocation tests

conformance_tests/tools/debug/src/test_debug.cpp
Timeout must be long enough to ensure application finished.
Signed-off-by: Brandon Yates <brandon.yates@intel.com
=> increase timeout at end of unavailable thread debug test

conformance_tests/core/test_event/src/test_event.cpp
Related-To: NEO-14632
Signed-off-by: Jaroslaw Warchulski <jaroslaw.warchulski@intel.com>
=> fix: set correct event descriptor signal in test_event

conformance_tests/core/test_copy/src/test_copy_image.cpp
Adjust originX and originY values in cases 11 and 12 in order to keep
sums of region originX and width as well as originY and height within
image boundaries.
Signed-off-by: Filip Hazubski <filip.hazubski@intel.com>
=> test_copy: Correct copy regions in cases 11 and 12

conformance_tests/sysman/test_sysman_events/src/test_sysman_events.cpp, conformance_tests/sysman/test_sysman_psu/src/test_sysman_psu.cpp, conformance_tests/sysman/test_sysman_ras/src/test_sysman_ras.cpp, utils/test_harness/sysman/include/test_harness_sysman_ras.hpp
Primary JIRA: [VLCJ-2513]
Sub-tasks: [VLCLJ-2574], [VLCLJ-2576], [VLCLJ-2567]
1. Updated the GTEST_FAIL logic for psu, ras and events modules. Implemented to check the handles for all the devices in multi-device scenario, and FAIL only if the handle is not found for any device.
2. Check the handles for each device and update the test to FAIL only if handles are not found for any device.
=> Fix: Handling GTEST_FAIL logic for multi-device scenario for PSU, RAS and EVENTS modules

conformance_tests/sysman/test_sysman_firmware/src/test_sysman_firmware.cpp, conformance_tests/sysman/test_sysman_led/src/test_sysman_led.cpp, conformance_tests/sysman/test_sysman_memory/src/test_sysman_memory.cpp
Primary JIRA: VLCLJ-2513
Sub-tasks: VLCLJ-2572, VLCLJ-2575, VLCLJ-2564
Update the GTEST_FAIL logic for led, memory and firmware modules. Implemented to check the handles for all the devices and FAIL only if the handle is not found for any device.
=> Fix: Handling GTEST_FAIL logic for multi-device scenario for LED, Memory and Firmware modules

conformance_tests/sysman/test_sysman_diagnostics/src/test_sysman_diagnostics.cpp, conformance_tests/sysman/test_sysman_fan/src/test_sysman_fan.cpp, conformance_tests/sysman/test_sysman_frequency/src/test_sysman_frequency.cpp
Primary JIRA: VLCLJ-2513
Sub-tasks: VLCLJ-2563, VLCLJ-2565, VLCLJ-2566
Update the GTEST_FAIL logic for frequency, diagnostics and fan modules.
Implemented to check the handles for all the devices and FAIL only if the handle is not found for any device.
=> Fix: Handling GTEST_FAIL logic for multi-device scenario for Fan, Diagnostics and Frequency modules

conformance_tests/sysman/test_sysman_performance/src/test_sysman_performance.cpp, conformance_tests/sysman/test_sysman_power/src/test_sysman_power.cpp, conformance_tests/sysman/test_sysman_scheduler/src/test_sysman_scheduler.cpp
Primary JIRA: VLCLJ-2513
Sub-tasks: VLCLJ-2570, VLCLJ-2568, VLCLJ-2577
Fix: Handling GTEST_FAIL logic for multi-device scenario for power, performance and scheduler modules.
=> Fix: Handling GTEST_FAIL logic for multi-device scenario for power, performance and scheduler modules

conformance_tests/core/test_cmdlist/src/test_cmdlist.cpp
Correct order of the arguments to match spill_test function.
Correct offset memory size.
Signed-off-by: Filip Hazubski <filip.hazubski@intel.com>
=> test_cmdlist: Correct spill_test arguments

utils/utils/include/utils/utils_gtest_helper.hpp
Signed-off-by: Oskar Hubert Weber <oskar.hubert.weber@intel.com>
=> refactor: typo
