- perf_tests/ze_peak/include/ze_peak.h
- perf_tests/ze_peak/src/ze_peak.cpp
Closes #8 
Signed-off-by:Brandon Yates <brandon.yates@intel.com>
> Allow device selection in ze_peak

- conformance_tests/sysman/test_sysman_device/src/test_sysman_device.cpp
- utils/test_harness/sysman/include/test_harness_sysman_device.hpp
- utils/test_harness/sysman/src/test_harness_sysman_device.cpp
New CTS cases for Sysman device mapping API zesDeviceGetSubDevicePropertiesExp
> New CTS cases for Sysman device mapping APIs

- conformance_tests/sysman/test_sysman_pci/src/test_sysman_pci.cpp
> fix: CTS bugs in Sysman PCI module

- conformance_tests/core/test_module/src/test_module.cpp
- conformance_tests/sysman/test_sysman_device/src/test_sysman_device_helper.cpp
- perf_tests/ze_peer/src/ze_peer.cpp
> Fix test static analysis issues

- conformance_tests/tools/debug/src/child_debugger.cpp
- conformance_tests/tools/debug/src/test_debug.cpp
- conformance_tests/tools/debug/src/test_debug_utils.cpp
- utils/test_harness/include/test_harness/zet_intel_gpu_debug.h
- utils/test_harness/tools/include/test_harness_debug.hpp
- utils/test_harness/tools/src/test_harness_debug.cpp
Signed-off-by: Jitendra Sharma <jitendra.sharma@intel.com>
> Debugger: Clear exceptions before resuming interrupted threads

- conformance_tests/sysman/test_sysman_temperature/src/test_sysman_temperature.cpp
Added min/max limit check for temperature in sysman temperature CTS
Related-To: [VLCLJ-2296](https://jira.devtools.intel.com/browse/VLCLJ-2296)
> Added min/max limit check for temperature in sysman temperature CTS

- conformance_tests/tools/metrics/src/test_metric.cpp
- utils/test_harness/tools/include/test_harness_metric.hpp
- utils/test_harness/tools/src/test_harness_metric.cpp
Resolves: [VLCLJ-2321](https://jira.devtools.intel.com/browse/VLCLJ-2321)
> fix: update metric tests

- conformance_tests/tools/metrics/src/test_metric.cpp
- utils/test_harness/tools/include/test_harness_metric.hpp
- utils/test_harness/tools/src/test_harness_metric.cpp
Reverts oneapi-src/level-zero-tests#94
> Revert "fix: update metric tests"

- conformance_tests/tools/metrics/src/test_metric.cpp
- utils/test_harness/tools/include/test_harness_metric.hpp
- utils/test_harness/tools/src/test_harness_metric.cpp
Resolves: [VLCLJ-2321](https://jira.devtools.intel.com/browse/VLCLJ-2321)
> fix: update metric query tests

- conformance_tests/sysman/test_sysman_events/src/test_sysman_events.cpp
- conformance_tests/sysman/test_sysman_frequency/src/test_sysman_frequency.cpp
- conformance_tests/sysman/test_sysman_power/src/test_sysman_power.cpp
- utils/test_harness/sysman/include/test_harness_sysman_power.hpp
- utils/test_harness/sysman/src/test_harness_sysman_power.cpp
> fix: Update power CTS to handle new GPU/Memory domains

- conformance_tests/tools/metrics/src/test_metric.cpp
- utils/test_harness/tools/include/test_harness_metric.hpp
- utils/test_harness/tools/src/test_harness_metric.cpp
Resolves: [VLCLJ-2324](https://jira.devtools.intel.com/browse/VLCLJ-2324)
> fix: update streamer marker tests

- conformance_tests/sysman/test_sysman_init/src/test_init_sysman.cpp
- conformance_tests/sysman/test_sysman_init/src/test_init_sysman_after_core.cpp
- conformance_tests/sysman/test_sysman_init/src/test_init_sysman_before_core.cpp
- conformance_tests/sysman/test_sysman_init/src/test_init_sysman_enum_freq_with_core_handle.cpp
- conformance_tests/sysman/test_sysman_init/src/test_init_sysman_enum_freq_with_sysman_handle.cpp
- conformance_tests/sysman/test_sysman_init/src/test_init_sysman_no_env_with_core_handle.cpp
- utils/test_harness/include/test_harness/test_harness_device.hpp
- utils/test_harness/src/test_harness_device.cpp
> refactor sysman init tests

- conformance_tests/sysman/test_sysman_frequency/src/test_sysman_frequency.cpp
- utils/test_harness/sysman/include/test_harness_sysman_frequency.hpp
- utils/test_harness/sysman/src/test_harness_sysman_frequency.cpp
> fix: bugs in Sysman Frequency CTS

- conformance_tests/sysman/test_sysman_pci/src/test_sysman_pci.cpp
> fix: bug in sysman pci stats CTS

- conformance_tests/tools/metrics/CMakeLists.txt
- conformance_tests/tools/metrics/src/test_metric_programmable.cpp
- conformance_tests/tools/metrics/src/test_metric_tracer.cpp
- scripts/level_zero_report_utils.py
- utils/test_harness/tools/include/test_harness_metric.hpp
- utils/test_harness/tools/src/test_harness_metric.cpp
Resolves: [VLCLJ-2338](https://jira.devtools.intel.com/browse/VLCLJ-2338)
> feat: add tracer and programmable tests

- conformance_tests/sysman/CMakeLists.txt
- conformance_tests/sysman/test_sysman_vf_management/CMakeLists.txt
- conformance_tests/sysman/test_sysman_vf_management/README.md
- conformance_tests/sysman/test_sysman_vf_management/src/main.cpp
- conformance_tests/sysman/test_sysman_vf_management/src/test_sysman_vf_management.cpp
- scripts/level_zero_report_utils.py
- utils/test_harness/CMakeLists.txt
- utils/test_harness/sysman/include/test_harness_sysman.hpp
- utils/test_harness/sysman/include/test_harness_sysman_vf_management.hpp
- utils/test_harness/sysman/src/test_harness_sysman_vf_management.cpp
> test: Add Sysman VF Management CTS

- conformance_tests/tools/metrics/src/test_metric_programmable.cpp
- conformance_tests/tools/metrics/src/test_metric_tracer.cpp
- utils/test_harness/tools/src/test_harness_metric.cpp
Related to commit cf41a5a6d220a5ca951f7d92e2d62f51d38fbb1c
> fix: address coverity issues in (oneapi-src#127)

- conformance_tests/tools/metrics/CMakeLists.txt
- scripts/level_zero_report_utils.py
Related to commit cf41a5a6d220a5ca951f7d92e2d62f51d38fbb1c
> fix: no separate test exec for (oneapi-src#127)

- conformance_tests/sysman/test_sysman_frequency/src/test_sysman_frequency.cpp
- conformance_tests/sysman/test_sysman_power/src/test_sysman_power.cpp
- utils/test_harness/sysman/include/test_harness_sysman_frequency.hpp
- utils/test_harness/sysman/include/test_harness_sysman_power.hpp
- utils/test_harness/sysman/src/test_harness_sysman_frequency.cpp
- utils/test_harness/sysman/src/test_harness_sysman_power.cpp
> test: Add CTS for Sysman Freq & Power telemetry collection Overhead

- conformance_tests/tools/debug/src/test_debug_helper.cpp
> Correctly take the input kernel options.

- conformance_tests/sysman/test_sysman_vf_management/src/test_sysman_vf_management.cpp
- utils/test_harness/sysman/include/test_harness_sysman_vf_management.hpp
- utils/test_harness/sysman/src/test_harness_sysman_vf_management.cpp
> fix: Update Sysman VF management CTS

- conformance_tests/tools/debug/src/test_debug.hpp
Signed-off-by: Jitendra Sharma <jitendra.sharma@intel.com>
> [EU Debug]: Increase eventsTimeoutMS

- conformance_tests/tools/metrics/src/test_metric_programmable.cpp
- utils/test_harness/tools/src/test_harness_metric.cpp
Related to [NEO-13780](https://jira.devtools.intel.com/browse/NEO-13780)
> fix: modify log verbosity for programmables

- conformance_tests/tools/debug/src/child_debugger.cpp
> Fix using uninitialized device thread

- conformance_tests/tools/debug/src/child_debugger.cpp
- conformance_tests/tools/debug/src/test_debug.cpp
- conformance_tests/tools/debug/src/test_debug.hpp
- conformance_tests/tools/debug/src/test_debug_common.hpp
- conformance_tests/tools/debug/src/test_debug_helper.cpp
- conformance_tests/tools/debug/src/test_debug_helper.hpp
> Increase number of threads in debugger test

- conformance_tests/sysman/test_sysman_device/src/test_sysman_device.cpp
> fix: Add Serial/Board Number validation check

- utils/test_harness/src/test_harness_module.cpp
* zeModuleCreate verifies format
> test_harness: remove redundant check

- conformance_tests/sysman/test_sysman_device/src/test_sysman_device.cpp
- conformance_tests/sysman/test_sysman_engine/src/test_sysman_engine.cpp
- conformance_tests/sysman/test_sysman_frequency/src/test_sysman_frequency.cpp
- conformance_tests/sysman/test_sysman_memory/src/test_sysman_memory.cpp
- conformance_tests/sysman/test_sysman_pci/src/test_sysman_pci.cpp
- utils/test_harness/sysman/include/test_harness_sysman_device.hpp
- utils/test_harness/sysman/src/test_harness_sysman_device.cpp
> fix: Make memory resident after allocation in Sysman CTS

- conformance_tests/tools/metrics/src/test_metric.cpp
- utils/test_harness/tools/include/test_harness_metric.hpp
- utils/test_harness/tools/src/test_harness_metric.cpp
Signed-off-by: shubham kumar <shubham.kumar@intel.com>
> test: Add CTS to validate buffer overflow for EUSS

- conformance_tests/tools/metrics/src/test_metric_tracer.cpp
- utils/test_harness/tools/include/test_harness_metric.hpp
- utils/test_harness/tools/src/test_harness_metric.cpp
Resolves: [VLCLJ-2391](https://jira.devtools.intel.com/browse/VLCLJ-2391)
> feat: create decoder behavioral tests

- conformance_tests/tools/metrics/src/test_metric.cpp
Related to [VLCLJ-2425](https://jira.devtools.intel.com/browse/VLCLJ-2425)
> fix: assert if metric query pool is absent

- conformance_tests/tools/metrics/src/test_metric.cpp
Signed-off-by: shubham kumar <shubham.kumar@intel.com>
> test: add env var for sleep in overflow test

- conformance_tests/tools/metrics/src/test_metric_tracer.cpp
- utils/test_harness/tools/include/test_harness_metric.hpp
- utils/test_harness/tools/src/test_harness_metric.cpp
Related to [VLCLJ-2347](https://jira.devtools.intel.com/browse/VLCLJ-2347)
> test: ensure event gen on kernel to dma buf write

- conformance_tests/tools/metrics/src/test_metric_tracer.cpp
Related to [VLCLJ-2399](https://jira.devtools.intel.com/browse/VLCLJ-2399)
> test: add metric tracer tests

- conformance_tests/tools/metrics/src/test_metric_programmable.cpp
- conformance_tests/tools/metrics/src/test_metric_tracer.cpp
- utils/test_harness/tools/include/test_harness_metric.hpp
- utils/test_harness/tools/src/test_harness_metric.cpp
Related to [VLCLJ-2395](https://jira.devtools.intel.com/browse/VLCLJ-2395)
> test: use metric tracer harness functions

- conformance_tests/core/test_cmdlist/src/test_cmdlist.cpp
- conformance_tests/core/test_cmdlist/src/test_cmdlist_immediate.cpp
- conformance_tests/core/test_cmdlist/src/test_cmdlist_mixed.cpp
- conformance_tests/core/test_module/src/test_cooperative_kernel.cpp
- conformance_tests/core/test_module/src/test_module.cpp
- scripts/level_zero_report_utils.py
- utils/test_harness/include/test_harness/test_harness_memory.hpp
- utils/test_harness/src/test_harness_memory.cpp
Related to [VLCLJ-2479](https://jira.devtools.intel.com/browse/VLCLJ-2479)
> test: add shared system allocator tests

- conformance_tests/core/test_cmdlist/src/test_cmdlist.cpp
- conformance_tests/core/test_copy/src/test_copy.cpp
- scripts/level_zero_report_utils.py
Related to [VLCLJ-2490](https://jira.devtools.intel.com/browse/VLCLJ-2490)
> test: shared system allocator tests for *MemoryFill

- conformance_tests/sysman/test_sysman_memory/src/test_sysman_memory.cpp
> test(Sysman):Test to ensure memory handle location is as expected.

- utils/test_harness/include/test_harness/test_harness_device.hpp
- utils/test_harness/src/test_harness_device.cpp
Signed-off-by: Alicja Lukaszewicz <alicja.lukaszewicz@intel.com>
> fix: update memory residency and eviction harness

- conformance_tests/core/test_usm/src/test_usm_atomic.cpp
Related to [VLCLJ-2522](https://jira.devtools.intel.com/browse/VLCLJ-2522)
> test: shared system test for *AtomicAccessAttr*

- conformance_tests/core/test_cmdlist/src/test_cmdlist_immediate.cpp
- conformance_tests/core/test_copy/src/test_copy.cpp
Related to [VLCLJ-2521](https://jira.devtools.intel.com/browse/VLCLJ-2521)
> test: shared system tests for *MemAdvise

- conformance_tests/core/test_cmdlist/src/test_cmdlist_immediate.cpp
- conformance_tests/core/test_cmdqueue/src/test_cmdqueue.cpp
- conformance_tests/core/test_event/src/test_event.cpp
Related-To: VCV-13070
Signed-off-by: Alicja Lukaszewicz <alicja.lukaszewicz@intel.com>
> fix: commands synchronization when calculating device responsiveness

- conformance_tests/sysman/test_sysman_device/src/test_sysman_device.cpp
> fix: Fix the Process State CTS

- conformance_tests/core/test_cmdlist/src/test_cmdlist_mixed.cpp
apply proper count of events to wait before launch kernel
Resolves: HSD-18043087394
> test_cmdlist: fix argument in append launch function

- .github/workflows/build-multi.yml
> Remove ubuntu 24.10 from infra

- conformance_tests/core/test_usm/src/test_usm_atomic.cpp
Resolves: [VLCLJ-2620](https://jira.devtools.intel.com/browse/VLCLJ-2620)
> fix: shared system atomic access attribute test
